name: polkawallet_plugin_karura
description: Karura network plugin for Polkawallet.
version: 0.3.1
homepage:

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  charts_flutter: ^0.10.0
  http: ^0.13.0
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  flutter_svg: ^0.22.0
  json_annotation: ^4.0.1
  get_storage: ^2.0.2
  device_info: ^2.0.1
  graphql_flutter: ^5.0.0-nullsafety.5
  liquid_progress_indicator: ^0.3.2
  polkawallet_sdk: ^0.3.1
  polkawallet_ui:
    #    path: ../ui
    git:
      url: https://github.com/polkawallet-io/ui.git
      ref: dec723c5c21849bb5629127ffbc4a84646c9b0bb

dev_dependencies:
  build_runner: ^2.0.3
  mobx_codegen: ^2.0.1+3
  json_serializable: ^4.1.2
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - lib/js_service_karura/dist/main.js
    - assets/images/bg.png
    - assets/images/assets_up.svg
    - assets/images/assets_down.svg
    - assets/images/assets_send.png
    - assets/images/tx_failed.svg
    - assets/images/swap.svg
    - assets/images/loan.svg
    - assets/images/loan-start.svg
    - assets/images/earn.svg
    - assets/images/scan.svg
    - assets/images/homa.svg
    - assets/images/nft.svg
    - assets/images/bifrost.png
    - assets/images/tokens/KAR.png
    - assets/images/tokens/KUSD.png
    - assets/images/tokens/KSM.png
    - assets/images/tokens/LKSM.png
    - assets/images/tokens/RENBTC.png
    - assets/images/tokens/XBTC.png
    - assets/images/tokens/POLKABTC.png
    - assets/images/tokens/PLM.png
    - assets/images/tokens/PHA.png
    - assets/images/logo_kar_gray.png
    - assets/images/logo_kar_empty.svg
    - assets/images/democracy.svg
